### ISSUE TITLE
access denied: channel [xxx] creator org

### ISSUE THREAD

**Issue by chebyte** [litong01/minifabric#73] opened 2020-09-19 17:13 UTC
Hello there, I just configured my network like this

````
minifab up -o hlf.hashdog.com -c rstorage -l node -n storage -v 1.0 -p '"initLedger",""' -e true
````
and works great, but then when I try to do a query using nodesdk and profile generated inside profile folder I get this error

````
{
  "code": 500,
  "timestamp": "9/19/2020",
  "path": "/query",
  "method": "POST",
  "message": "Failed to evaluate transaction: FabricError: Query failed. Errors: [\"Error: 2 UNKNOWN: error validating proposal: access denied: channel [rstorage] creator org [hlf-hashdog-com]\"]"
}
````

anyone know what is the problem?

my spec file
````
fabric:
  cas:
  - "ca0.hlf.hashdog.com"
  peers:
  - "peer0.hlf.hashdog.com"
  orderers:
  - "orderer0.hashdog.com"
  settings:
    ca:
      FABRIC_LOGGING_SPEC: DEBUG
    peer:
      FABRIC_LOGGING_SPEC: DEBUG
    orderer:
      FABRIC_LOGGING_SPEC: DEBUG
  
````

my profile

````
{
  "name": "fabric-network",
  "x-type": "hlfv1",
  "version": "1.0.0",
  "channels": {
    "rstorage": {
      "orderers": [
        "orderer0.hashdog.com"
      ],
      "peers": [
        "peer0.hlf.hashdog.com"
      ]
    }
  },
  "organizations": {
    "hashdog.com": {
      "mspid": "hashdog-com",
      "peers": [],
      "orderers": [
        "orderer0.hashdog.com"
      ]
    },
    "hlf.hashdog.com": {
      "mspid": "hlf-hashdog-com",
      "peers": [
        "peer0.hlf.hashdog.com"
      ],
      "orderers": [],
      "certificateAuthorities": [
        "ca0.hlf.hashdog.com"
      ]
    }
  },
  "orderers": {
    "orderer0.hashdog.com": {
      "url": "grpcs://157.230.48.21:7002",
      "grpcOptions": {
        "ssl-target-name-override": "orderer0.hashdog.com"
      },
      "tlsCACerts": {
        "pem": "-----BEGIN CERTIFICATE-----\nxxxx\n-----END CERTIFICATE-----"
      }
    }
  },
  "peers": {
    "peer0.hlf.hashdog.com": {
      "url": "grpcs://157.230.48.21:7001",
      "grpcOptions": {
        "ssl-target-name-override": "peer0.hlf.hashdog.com"
      },
      "tlsCACerts": {
        "pem": "-----BEGIN CERTIFICATE-----\nxxxx\n-----END CERTIFICATE-----"
      }
    }
  },
  "certificateAuthorities": {
    "ca0.hlf.hashdog.com": {
      "url": "https://157.230.48.21:7000",
      "tlsCACerts": {
        "path": "/keyfiles/peerOrganizations/hlf.hashdog.com/ca/ca0.hlf.hashdog.com-cert.pem"
      },
      "httpOptions": {
        "verify": "false"
      },
      "caName": "ca0",
      "registrar": {
        "enrollId": "admin",
        "enrollSecret": "adminpw"
      }
    }
  },
  "entityMatchers": {
    "orderer": [
      {
        "mappedHost": "orderer0.hashdog.com",
        "pattern": "(\\w*)orderer0.hashdog.com(\\w*)",
        "sslTargetOverrideUrlSubstitutionExp": "orderer0.hashdog.com",
        "urlSubstitutionExp": "157.230.48.21:7002"
      }
    ],
    "peer": [
      {
        "mappedHost": "peer0.hlf.hashdog.com",
        "pattern": "(\\w*)peer0.hlf.hashdog.com(\\w*)",
        "sslTargetOverrideUrlSubstitutionExp": "peer0.hlf.hashdog.com",
        "urlSubstitutionExp": "157.230.48.21:7001"
      }
    ],
    "certificateAuthorities": [
      {
        "mappedHost": "ca0.hlf.hashdog.com",
        "pattern": "(\\w*)ca0.hlf.hashdog.com(\\w*)",
        "sslTargetOverrideUrlSubstitutionExp": "ca0.hlf.hashdog.com",
        "urlSubstitutionExp": "157.230.48.21:7000"
      }
    ]
  }
}
````

thanks for advance

**Comment by litong01** [comment] 2020-09-21 13:30
@chebyte I am not quite sure the cause of the error. Seems to me that the user you were using to do transaction may have not been right. You can look at this the sample app in minifabric/app directory, the file name is app.js and you can actually try that app using caliperrun command.

**Comment by litong01** [comment] 2020-09-22 13:40
@chebyte any new information on this? there isn't much I can go on with.

**Comment by litong01** [comment] 2020-09-24 12:11
@chebyte any updates on this? If no updates, then I will assume that you have resolved your issue, I will close this. BTW, I've add apprun capability to minifabric, you can look at the feature and on how to use it in docs/README.md file.

**Comment by litong01** [comment] 2020-09-26 00:54
No activity for days. Closing this.

**Closed** 2020-09-26 00:54 UTC
